DROP TABLE IF EXISTS dropdown;
DROP TABLE IF EXISTS dropdownGroup;

CREATE TABLE dropdown (
    id INT AUTO_INCREMENT PRIMARY KEY,
    groupId INT NOT NULL,
    orgId INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    crdtDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updtDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dropdownGroup (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orgId INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    crdtDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updtDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);