const joi = require("@hapi/joi")
const schema = {
    createStudent: joi.object({
        orgId: joi.string().required(),
        crdtBy: joi.string().required(),
        firstname: joi.string().required(),
        middelname: joi.string().allow('').allow(null),
        lastname: joi.string().required(),
        email: joi.string().email().required(),
        mobile: joi.number().required(),
        address: joi.string().required(),
        gender: joi.string().required(),
        dob: joi.date().required(),
        checkIn: joi.date().allow('').allow(null),
        checkOut: joi.date().allow('').allow(null),
        categoryId: joi.string().required(),
        meals: joi. number().allow('').allow(null),
        fatherName: joi.string().required(),
        rollNumber: joi.string().required(),
        fatherMobile: joi.number().allow('').allow(null),
        motherName: joi.string().allow('').allow(null),
        motherMobile: joi.number().allow('').allow(null),
        parentEmail: joi.string().email().allow('').allow(null),
        hostel: joi.string().allow('').allow(null),
        guardianName: joi.string().allow('').allow(null),
        guardianMobile: joi.number().allow('').allow(null),
        roomNumber: joi.string().allow('').allow(null),
        batchId: joi.string().required(),
        classId: joi.string().required(),
        semesterId: joi.string().required()
    }),
    updateStudent: joi.object({
        orgId: joi.string().required(),
        crdtBy: joi.string().required(),
        firstname: joi.string().required(),
        middelname: joi.string().allow('').allow(null),
        lastname: joi.string().required(),
        email: joi.string().email().required(),
        mobile: joi.number().required(),
        address: joi.string().required(),
        gender: joi.string().required(),
        dob: joi.date().required(),
        checkIn: joi.date().allow('').allow(null),
        checkOut: joi.date().allow('').allow(null),
        meals: joi. number().allow('').allow(null),
        categoryId: joi.string().required(),
        fatherName: joi.string().required(),
        rollNumber: joi.string().required(),
        fatherMobile: joi.number().allow('').allow(null),
        motherName: joi.string().allow('').allow(null),
        motherMobile: joi.number().allow('').allow(null),
        parentEmail: joi.string().email().allow('').allow(null),
        hostel: joi.string().allow('').allow(null),
        guardianName: joi.string().allow('').allow(null),
        guardianMobile: joi.number().allow('').allow(null),
        roomNumber: joi.string().allow('').allow(null),
        batchId: joi.string().required(),
        classId: joi.string().required(),
        semesterId: joi.string().required()
    })
}
module.exports = schema